language: node_js

before_install:
  - rvm install

install:
  - make npm
  - make bundler

notifications:
  - false

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
    - npm run cy:info

script:
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
  - $(npm bin)/print-env TRAVIS
  - npm run start:ci &
  - npm run cy:run -- --record --parallel --group $STAGE_NAME

after_success:
  - CI=true TRAVIS=true coveralls --verbose
